### ISSUE TITLE
Лицензия?

### ISSUE THREAD

**Issue by baydet** [juniororienteeringblr/map-cdodim-kontakt#1]
Свободный доступ - это очень круто! Но в то же время очень важно, чтобы у проекта была лицензия. Чтобы люди понимали какие права у них есть на этот продукт и за что их потом не будут преследовать :) Если не заморачиваться, то можно ограничиться MIT
https://ru.wikipedia.org/wiki/Лицензия_MIT

**Comment by hannarud** [comment]
Почитала немного в интернете. MIT - она все же для ПО, а тут не совсем ПО, тут произведение искусства. Поэтому добавила лицензию Creative Commons (https://creativecommons.org/licenses/by/4.0/deed.ru) - что скажешь - права я?

**Comment by baydet** [comment]
Seems legit! Да, я потом тоже подумал, что MIT не очень подходит для такого продукта. Про Creative Commons не вспомнил тогда.
